language: ruby
sudo: false

rvm:
- 2.5.5

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer


cache: bundler

script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --disable_external
