title: Spotify Moodboard by Ömer Ayyıldız
author: Ömer Ayyıldız
email: oayyildiz416@gmail.com
description: >-
  Spotify is my inspiration. This website is my painting bag. Enjoy it :)

social:
  github: omerayyildiz

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
